[package]
name = "windows-rs-game-of-life"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.18"
bindings = { path = "bindings" }

anyhow = "1.0"

rand = "0.8"
